INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('user', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi');
INSERT INTO USERS (USERNAME, PASSWORD) VALUES ('jdoe', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi');

INSERT INTO AUTH_USERS_GROUP (USERNAME, AUTH_GROUP) VALUES('user', 'USER');
INSERT INTO AUTH_USERS_GROUP (USERNAME, AUTH_GROUP) VALUES('user', 'ADMIN');
INSERT INTO AUTH_USERS_GROUP (USERNAME, AUTH_GROUP) VALUES('jdoe', 'USER');